name: Todo frontend pipeline
on:
    push:
      branches:
        - feature
  
jobs:
    build:
      env: # Set the secret as an input
        Username: 123
        Password: 123
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag betselot456/todo-front-angular
      - name: login to Docker
        run: |
             docker login -u $Username -p $Password
      - name: Push image to Registry
        run: docker push betselot456/todo-front-angular

    # deploy:
    #     runs-on: ubuntu-latest
    #     needs: build
    #     steps:

