name: Todo frontend pipeline
on:
    push:
      branches:
        - feature
  
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag todo-front-angular:$(date +%s)
      - name: test 
        run: echo ${{env.USERNAME}} 
      - name: login to Docker
        run: docker login -u ${{env.USERNAME}} -p ${{env.PASSWORD}}
      - name: Push image to Registry
        run: docker push $DOCKER_IMAGE

    # deploy:
    #     runs-on: ubuntu-latest
    #     needs: build
    #     steps:

