name: Todo frontend pipeline
on:
    push:
      branches:
        - feature
  
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: login to Docker
        run: docker login -u ${{secrets.USERNAME}}" -p ${{secrets.PASSWORD}}"
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag todo-front-angular:$(date +%s)
      - name: Push image to Registry
        run: docker push $DOCKER_IMAGE



